<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SptModManager.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SemanticVersioning" Version="3.0.0" />
    <PackageReference Include="SharpCompress" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SptModManager.Core.Tests" />
  </ItemGroup>

</Project>
